# Generated by Django 4.2.1 on 2023-05-21 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dateOfActual', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('num', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('isEmpty', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('auto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ParkingApp.auto')),
            ],
            options={
                'verbose_name': 'Parking place',
                'verbose_name_plural': 'Parking places',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(default='+375 (29) xxx-xx-xx', max_length=20, validators=[django.core.validators.RegexValidator(regex='^+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cars', models.ManyToManyField(to='ParkingApp.auto')),
                ('checks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ParkingApp.check')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ParkingApp.parkingplace'),
        ),
    ]
