# Generated by Django 4.2.1 on 2023-05-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='auto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ParkingApp.auto'),
        ),
    ]
